const estadios = [
    {
        id: 1,
        nombre: 'Estadio Centenario',
        capacidad: 60235,
        propietario: 'Asociación Uruguaya de Fútbol',
        imagen: 'https://i.postimg.cc/sDcMszy6/centenario.webp',
        inauguracion: 1930,
        localidad: 'Parque Batlle',
        departamento: 'Montevideo',
        wikipedia: 'http://www.estadiocentenario.com.uy/'
    },
    {
        id: 2,
        nombre: 'Estadio Campeón del Siglo',
        capacidad: 40705,
        propietario: 'Club Atlético Peñarol',
        imagen: 'https://i.postimg.cc/3xfW0Zk2/cds.png',
        inauguracion: 2016,
        localidad: 'Bañados de Carrasco',
        departamento: 'Montevideo',
        wikipedia: 'https://www.peñarol.org/categoria/Estadio-159/'
    },
    {
        id: 3,
        nombre: 'Gran Parque Central',
        capacidad: 34000,
        propietario: 'Club Nacional de Football',
        imagen: 'https://i.postimg.cc/NGxsrxVL/gpc.png',
        inauguracion: 1900,
        localidad: 'La Blanqueada',
        departamento: 'Montevideo',
        wikipedia: 'https://nacional.uy/es/club/instalaciones/gran-parque-central/'
    },
    {
        id: 4,
        nombre: 'Estadio Atilio Paiva Olivera',
        capacidad: 27135,
        propietario: 'Intendencia Municipal de Rivera',
        imagen: 'https://i.postimg.cc/2y9g73h9/paiva.png',
        inauguracion: 1927,
        localidad: 'Rivera',
        departamento: 'Rivera',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Atilio_Paiva_Olivera'
    },
    {
        id: 5,
        nombre: 'Estadio Monumental Luis Tróccoli',
        capacidad: 25000,
        propietario: 'Club Atlético Cerro',
        imagen: 'https://i.postimg.cc/x8X6Y5Ng/troccoli.jpg',
        inauguracion: 1964,
        localidad: 'Villa del Cerro',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Luis_Tr%C3%B3ccoli'
    },
    {
        id: 6,
        nombre: 'Estadio Artigas',
        capacidad: 25000,
        propietario: 'Intendencia Municipal de Paysandú',
        imagen: 'https://i.postimg.cc/Cx5x0fc5/estadio-artigas.jpg',
        inauguracion: 1927,
        localidad: 'Paysandú',
        departamento: 'Paysandú',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Artigas_(Paysand%C3%BA)'
    },
    {
        id: 7,
        nombre: 'Estadio María Mincheff de Lazaroff',
        capacidad: 18000,
        propietario: 'Danubio Fútbol Club',
        imagen: 'https://i.postimg.cc/sgMsqC2Z/jardines.jpg',
        inauguracion: 1957,
        localidad: 'Jardines del Hipódromo',
        departamento: 'Montevideo',
        wikipedia: 'http://www.danubio.org.uy/uc_24_1.html'
    },
    {
        id: 8,
        nombre: 'Estadio Domingo Burgueño Miguel',
        capacidad: 17172,
        propietario: 'Intendencia Municipal de Maldonado',
        imagen: 'https://i.postimg.cc/tJFVhnKp/campus.jpg',
        inauguracion: 1994,
        localidad: 'Maldonado',
        departamento: 'Maldonado',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Domingo_Burgue%C3%B1o_Miguel'
    },
    {
        id: 9,
        nombre: 'Estadio Luis Franzini',
        capacidad: 16000,
        propietario: 'Defensor Sporting Club',
        imagen: 'https://i.postimg.cc/PJKdstZ1/franzini.png',
        inauguracion: 1963,
        localidad: 'Parque Rodó',
        departamento: 'Montevideo',
        wikipedia: 'https://defensorsporting.com.uy/institucion/sedes-y-complejos/estadio-luis-franzini/'
    },
    {
        id: 10,
        nombre: 'Estadio Cr. José Pedro Damiani',
        capacidad: 12000,
        propietario: 'Club Atlético Peñarol',
        imagen: 'https://i.postimg.cc/jS1dSd1X/damiani.jpg',
        inauguracion: 1916,
        localidad: 'Las Acacias',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Jos%C3%A9_Pedro_Damiani'
    },
    {
        id: 11,
        nombre: 'Estadio Charrúa',
        capacidad: 11226,
        propietario: 'Intendencia Municipal de Montevideo',
        imagen: 'https://i.postimg.cc/C50KpP2p/charrua.png',
        inauguracion: 1984,
        localidad: 'Parque Rivera',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Charr%C3%BAa'
    },
    {
        id: 12,
        nombre: 'Estadio Municipal Parque Liebig\'s',
        capacidad: 10000,
        propietario: 'Intendencia Municipal de Río Negro',
        imagen: 'https://i.postimg.cc/kGMdykZG/liebigs.jpg',
        inauguracion: 1960,
        localidad: 'Fray Bentos',
        departamento: 'Río Negro',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_Parque_Liebig%27s'
    },
    {
        id: 13,
        nombre: 'Complejo Rentistas',
        capacidad: 8232,
        propietario: 'Club Atlético Rentistas',
        imagen: 'https://i.postimg.cc/y8crkLQb/rentistas.jpg',
        inauguracion: 1998,
        localidad: 'Manga',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Complejo_Rentistas'
    },
    {
        id: 14,
        nombre: 'Estadio Silvestre Octavio Landoni',
        capacidad: 8000,
        propietario: 'Intendencia Municipal de Durazno',
        imagen: 'https://i.postimg.cc/PxjHCLQm/landoni.jpg',
        inauguracion: 1952,
        localidad: 'Durazno',
        departamento: 'Durazno',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Silvestre_Octavio_Landoni'
    },
    {
        id: 15,
        nombre: 'Estadio Municipal Juan Antonio Lavalleja',
        capacidad: 8000,
        propietario: 'Intendencia Municipal de Lavalleja',
        imagen: 'https://i.postimg.cc/bJ9hkzm4/lavalleja-minas.jpg',
        inauguracion: 1956,
        localidad: 'Minas',
        departamento: 'Lavalleja',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Juan_Antonio_Lavalleja_(Minas)'
    },
    {
        id: 16,
        nombre: 'Estadio Miguel Campomar',
        capacidad: 8000,
        propietario: 'Club Cyssa',
        imagen: 'https://i.postimg.cc/L4PfdGnw/campomar.jpg',
        inauguracion: 1945,
        localidad: 'Juan Lacaze',
        departamento: 'Colonia',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Miguel_Campomar'
    },
    {
        id: 17,
        nombre: 'Estadio Luis Köster',
        capacidad: 8000,
        propietario: 'Intendencia Municipal de Soriano',
        imagen: 'https://i.postimg.cc/kX17Tg7m/koster.jpg',
        inauguracion: 1954,
        localidad: 'Mercedes',
        departamento: 'Soriano',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Luis_K%C3%B6ster'
    },
    {
        id: 18,
        nombre: 'Estadio Belvedere',
        capacidad: 7780,
        propietario: 'Liverpool Fútbol Club',
        imagen: 'https://i.postimg.cc/pXtjPkjT/belvedere.jpg',
        inauguracion: 1909,
        localidad: 'Belvedere',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Belvedere'
    },
    {
        id: 19,
        nombre: 'Estadio Alfredo Víctor Viera',
        capacidad: 7243,
        propietario: 'Montevideo Wanderers Fútbol Club',
        imagen: 'https://i.postimg.cc/jjRvCtJD/viera.png',
        inauguracion: 1933,
        localidad: 'Prado',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Alfredo_V%C3%ADctor_Viera'
    },
    {
        id: 20,
        nombre: 'Estadio Municipal Arq. Antonio Eleuterio Ubilla',
        capacidad: 7000,
        propietario: 'Intendencia Municipal de Cerro Largo',
        imagen: 'https://i.postimg.cc/D0RBzGqh/ubilla.jpg',
        inauguracion: 1942,
        localidad: 'Melo',
        departamento: 'Cerro Largo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_Arquitecto_Antonio_Eleuterio_Ubilla'
    },
    {
        id: 21,
        nombre: 'Estadio Juan Antonio Lavalleja',
        capacidad: 7000,
        propietario: 'Intendencia Municipal de Flores',
        imagen: 'https://i.postimg.cc/pXTH5Mz1/lavalleja-trinidad.jpg',
        inauguracion: 1960,
        localidad: 'Trinidad',
        departamento: 'Flores',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Juan_Antonio_Lavalleja_(Trinidad)'
    },
    {
        id: 22,
        nombre: 'Estadio Municipal Matías González',
        capacidad: 7000,
        propietario: 'Intendencia Municipal de Artigas',
        imagen: 'https://i.postimg.cc/4xHRwv86/matias-gonzalez.jpg',
        inauguracion: '',
        localidad: 'Artigas',
        departamento: 'Artigas',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Mat%C3%ADas_Gonz%C3%A1lez'
    },
    {
        id: 23,
        nombre: 'Estadio Atenas',
        capacidad: 6500,
        propietario: 'Club Atlético Atenas',
        imagen: 'https://i.postimg.cc/Cxhfq1mp/atenas.jpg',
        inauguracion: 1955,
        localidad: 'San Carlos',
        departamento: 'Maldonado',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Ateniense'
    },
    {
        id: 24,
        nombre: 'Estadio Ernesto J. Dickinson',
        capacidad: 6500,
        propietario: 'Liga Salteña de Fútbol',
        imagen: 'https://i.postimg.cc/4dV3MkB1/dickinson.jpg',
        inauguracion: 1932,
        localidad: 'Salto',
        departamento: 'Salto',
        wikipedia: 'https://www.eswiki.org/wiki/Estadio_Ernesto_Dickinson'
    },
    {
        id: 25,
        nombre: 'Estadio Olímpico Pedro Arispe',
        capacidad: 6190,
        propietario: 'Rampla Juniors Football Club',
        imagen: 'https://i.postimg.cc/L6B15fkV/arispe.jpg',
        inauguracion: 1923,
        localidad: 'Villa del Cerro',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Ol%C3%ADmpico_Pedro_Arispe'
    },
    {
        id: 26,
        nombre: 'Campus Municipal Profesor Alberto Suppici',
        capacidad: 6168,
        propietario: 'Intendencia Municipal de Colonia',
        imagen: 'https://i.postimg.cc/2jtHGsgt/suppici.png',
        inauguracion: 1977,
        localidad: 'Colonia del Sacramento',
        departamento: 'Colonia',
        wikipedia: 'https://es.wikipedia.org/wiki/Campus_Municipal_Profesor_Alberto_Suppici'
    },
    {
        id: 27,
        nombre: 'Estadio Ing. Raúl Saturnino Goyenola',
        capacidad: 6156,
        propietario: 'Intendencia Municipal de Tacuarembó',
        imagen: 'https://i.postimg.cc/C5wwQZZF/goyenola.png',
        inauguracion: 1955,
        localidad: 'Tacuarembó',
        departamento: 'Tacuarembó',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Ra%C3%BAl_Goyenola'
    },
    {
        id: 28,
        nombre: 'Estadio Juventud Parque Artigas',
        capacidad: 6148,
        propietario: 'Club Atlético Juventud de Las Piedras',
        imagen: 'https://i.postimg.cc/Prrtbwsy/juventud.jpg',
        inauguracion: 2008,
        localidad: 'Las Piedras',
        departamento: 'Canelones',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Juventud_Parque_Artigas'
    },
    {
        id: 29,
        nombre: 'Estadio Eduardo Martínez Monegal',
        capacidad: 6000,
        propietario: 'Intendencia Municipal de Canelones',
        imagen: 'https://i.postimg.cc/QMLGzBPR/martinez-monegal.jpg',
        inauguracion: 1935,
        localidad: 'Canelones',
        departamento: 'Canelones',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Mart%C3%ADnez_Monegal'
    },
    {
        id: 30,
        nombre: 'Parque Julio Pozzi',
        capacidad: 6000,
        propietario: 'Intendencia Municipal de Salto',
        imagen: null,
        inauguracion: 1932,
        localidad: 'Salto',
        departamento: 'Salto',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Julio_Pozzi'
    },
    {
        id: 31,
        nombre: 'Estadio Centro Empleados de Comercio',
        capacidad: 6000,
        propietario: 'Intendencia Municipal de Treinta y Tres',
        imagen: 'https://i.postimg.cc/RVXZ2TQ2/empleados-comercio.jpg',
        inauguracion: 1970,
        localidad: 'Treinta y Tres',
        departamento: 'Treinta y Tres',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Empleados_del_Comercio'
    },
    {
        id: 32,
        nombre: 'Estadio Municipal Dr. Mario Sobrero',
        capacidad: 5552,
        propietario: 'Intendencia Municipal de Rocha',
        imagen: 'https://i.postimg.cc/hjPCZcSk/sobrero.jpg',
        inauguracion: 1955,
        localidad: 'Rocha',
        departamento: 'Rocha',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_Doctor_Mario_Sobrero'
    },
    {
        id: 33,
        nombre: 'Estadio Gustavo Ferraz',
        capacidad: 5500,
        propietario: 'Salto Nuevo Fútbol Club',
        imagen: null,
        inauguracion: 2004,
        localidad: 'Salto',
        departamento: 'Salto',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Gustavo_Ferraz'
    },
    {
        id: 34,
        nombre: 'Parque Capurro',
        capacidad: 5500,
        propietario: 'Centro Atlético Fénix',
        imagen: 'https://i.postimg.cc/jdKDp2Vn/capurro.png',
        inauguracion: 1938,
        localidad: 'Capurro',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Capurro'
    },
    {
        id: 35,
        nombre: 'Parque Federico Omar Saroldi',
        capacidad: 5165,
        propietario: 'Club Atlético River Plate',
        imagen: 'https://i.postimg.cc/d1H5zp3L/saroldi.png',
        inauguracion: 1928,
        localidad: 'Prado',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Federico_Omar_Saroldi'
    },
    {
        id: 36,
        nombre: 'Estadio Campeones Olímpicos',
        capacidad: 5124,
        propietario: 'Intendencia Municipal de Florida',
        imagen: 'https://i.postimg.cc/7ZZfLRZx/campeones-olimpicos.png',
        inauguracion: 1927,
        localidad: 'Florida',
        departamento: 'Florida',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Campeones_Ol%C3%ADmpicos'
    },
    {
        id: 37,
        nombre: 'Estadio José Nasazzi',
        capacidad: 5002,
        propietario: 'Club Atlético Bella Vista',
        imagen: 'https://i.postimg.cc/cHmp6FHS/nasazzi.png',
        inauguracion: 1931,
        localidad: 'Prado',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Jos%C3%A9_Nasazzi'
    },
    {
        id: 38,
        nombre: 'Estadio Obdulio Varela',
        capacidad: 5000,
        propietario: 'Club Social y Deportivo Villa Española',
        imagen: 'https://i.postimg.cc/rFbvd08K/obdulio-varela.jpg',
        inauguracion: 2002,
        localidad: 'Parque Guaraní',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Obdulio_Varela'
    },
    {
        id: 39,
        nombre: 'Estadio "La Bombonera"',
        capacidad: 5000,
        propietario: 'Club Atlético Basáñez',
        imagen: 'https://i.postimg.cc/Ls7qwVRm/bombonera.png',
        inauguracion: 1981,
        localidad: 'Malvín Norte',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_La_Bombonera_(Montevideo)'
    },
    {
        id: 40,
        nombre: 'Parque Osvaldo Roberto',
        capacidad: 4500,
        propietario: 'Racing Club de Montevideo',
        imagen: 'https://i.postimg.cc/yYwb1MPR/parque-roberto.png',
        inauguracion: 1941,
        localidad: 'Sayago',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Osvaldo_Roberto'
    },
    {
        id: 41,
        nombre: 'Parque Palermo',
        capacidad: 4072,
        propietario: 'Central Español Fútbol Club',
        imagen: 'https://i.postimg.cc/HxBNTjZW/parque-palermo.jpg',
        inauguracion: 1937,
        localidad: 'Parque Batlle',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Palermo'
    },
    {
        id: 42,
        nombre: 'Estadio Luis Méndez Piana',
        capacidad: 4000,
        propietario: 'Club Sportivo Miramar Misiones',
        imagen: 'https://i.postimg.cc/SKWFbSbj/mendez-piana.jpg',
        inauguracion: 1958,
        localidad: 'Parque Batlle',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Luis_M%C3%A9ndez_Piana'
    },
    {
        id: 43,
        nombre: 'Parque Salus',
        capacidad: 4000,
        propietario: 'Salus Football Club',
        imagen: 'https://i.postimg.cc/rp9n9KLG/parque-salus.png',
        inauguracion: '1971',
        localidad: 'Nuevo París',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Salus'
    },
    {
        id: 44,
        nombre: 'Estadio Emilio "Tito" López López',
        capacidad: 4000,
        propietario: 'Intendencia Municipal de Canelones',
        imagen: 'https://i.postimg.cc/L6bMzQV4/lopez-lopez.jpg',
        inauguracion: '',
        localidad: 'Pando',
        departamento: 'Canelones',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_de_Pando'
    },
    {
        id: 45,
        nombre: 'Estadio Municipal El Tenis',
        capacidad: 4000,
        propietario: 'Intendencia Municipal de Rocha',
        imagen: 'https://i.postimg.cc/Prtq67Zm/el-tenis.png',
        inauguracion: '',
        localidad: 'Rocha',
        departamento: 'Rocha',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_El_Tenis'
    },
    {
        id: 46,
        nombre: 'Estadio Samuel Prilliac',
        capacidad: 4000,
        propietario: 'Intendencia Municipal de Rocha',
        imagen: 'https://i.postimg.cc/Yq4Pwr1k/prilliac.jpg',
        inauguracion: '',
        localidad: 'Chuy',
        departamento: 'Rocha',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_del_Chuy'
    },
    {
        id: 47,
        nombre: 'Estadio Juan José Vispo Mari',
        capacidad: 4000,
        propietario: 'Liga de las Colonias Agrarias de Salto',
        imagen: 'https://i.postimg.cc/VkQKQjfB/vispo-mari.jpg',
        inauguracion: '1967',
        localidad: 'Salto',
        departamento: 'Salto',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Juan_Jos%C3%A9_Vispo_Mari'
    },
    {
        id: 48,
        nombre: 'Estadio Municipal Casto Martínez Laguarda',
        capacidad: 3810,
        propietario: 'Intendencia Municipal de San José',
        imagen: 'https://i.postimg.cc/wBJHx5Lq/laguarda.png',
        inauguracion: 1943,
        localidad: 'San José de Mayo',
        departamento: 'San José',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Municipal_Casto_Mart%C3%ADnez_Laguarda'
    },
    {
        id: 49,
        nombre: 'Estadio Walter Martinez Cerruti',
        capacidad: 3500,
        propietario: 'Con los mismos colores FC',
        imagen: 'https://i.postimg.cc/GpBtFsDV/cerruti.png',
        inauguracion: '',
        localidad: 'Bella Union',
        departamento: 'Artigas',
        wikipedia: 'https://bishopjimarends.com/estadio-walter-martinez-cerrutti-16189271843397292310/'
    },
    {
        id: 50,
        nombre: 'Parque Maracaná',
        capacidad: 3364,
        propietario: 'Club Sportivo Cerrito',
        imagen: 'https://i.postimg.cc/wv6PKDkb/parque-maracana.jpg',
        inauguracion: 2008,
        localidad: 'Casavalle',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Maracan%C3%A1'
    },
    {
        id: 51,
        nombre: 'Estadio Abraham Paladino',
        capacidad: 3200,
        propietario: 'Club Atlético Progreso',
        imagen: 'https://i.postimg.cc/s2CqckGz/paladino.jpg',
        inauguracion: 1926,
        localidad: 'La Teja',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Abraham_Paladino'
    },
    {
        id: 52,
        nombre: 'Parque Huracán',
        capacidad: 3084,
        propietario: 'Club Social y Deportivo Huracán Buceo',
        imagen: 'https://i.postimg.cc/52CD840p/parque-huracan.jpg',
        inauguracion: 1985,
        localidad: 'Unión',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Hurac%C3%A1n'
    },
    {
        id: 53,
        nombre: 'Parque Cincuentenario Juan G. Prandi',
        capacidad: 3000,
        propietario: 'Club Plaza Colonia de Deportes',
        imagen: 'https://i.postimg.cc/9f2gTysF/prandi.jpg',
        inauguracion: 1967,
        localidad: 'Colonia del Sacramento',
        departamento: 'Colonia',
        wikipedia: 'https://es.wikipedia.org/wiki/Parque_Cincuentenario_Juan_G._Prandi'
    },
    {
        id: 54,
        nombre: 'Estadio Víctor Della Valle',
        capacidad: 2500,
        propietario: 'Centro Cultural y Deportivo El Tanque Sisley',
        imagen: 'https://i.postimg.cc/6QD3Y5L3/della-valle.jpg',
        inauguracion: '1992',
        localidad: 'Carrasco Norte',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_V%C3%ADctor_Della_Valle'
    },
    {
        id: 55,
        nombre: 'Parque Carlos Ángel Fossa ("El Fortín")',
        capacidad: 2466,
        propietario: 'Institución Atlética Sud América',
        imagen: 'https://i.postimg.cc/90BQmP3R/el-fortin.png',
        inauguracion: 1935,
        localidad: 'Pérez Castellanos',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Carlos_%C3%81ngel_Fossa'
    },
    {
        id: 56,
        nombre: 'Parque Alfredo García Montero',
        capacidad: 2165,
        propietario: 'Lavalleja Fútbol Club',
        imagen: 'https://i.postimg.cc/JhB7DCVW/garcia-montero.jpg',
        inauguracion: 1944,
        localidad: 'Minas',
        departamento: 'Lavalleja',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Complejo_Lavalleja'
    },
    {
        id: 57,
        nombre: 'Parque El Balneario',
        capacidad: 2000,
        propietario: 'Club Deportivo Parque del Plata',
        imagen: 'https://i.postimg.cc/SQLsf4XS/el-balneario.jpg',
        inauguracion: 1960,
        localidad: 'Parque del Plata',
        departamento: 'Canelones',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_El_Balneario'
    },
    {
        id: 58,
        nombre: 'Parque Pedro Ángel Bossio',
        capacidad: 2000,
        propietario: 'Huracán Fútbol Club',
        imagen: 'https://i.postimg.cc/Pf6GjV9b/parque-bossio.jpg',
        inauguracion: 1972,
        localidad: 'Paso de la Arena',
        departamento: 'Montevideo',
        wikipedia: '#'
    },
    {
        id: 59,
        nombre: 'Parque Ancap',
        capacidad: 1500,
        propietario: 'Uruguay Montevideo Football Club',
        imagen: 'https://i.postimg.cc/kXD0XFP0/parque-ancap.jpg',
        inauguracion: 1991,
        localidad: 'Pueblo Victoria',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_ANCAP'
    },
    {
        id: 60,
        nombre: 'Parque Oriental',
        capacidad: 1500,
        propietario: 'Club Oriental de Football',
        imagen: 'https://i.postimg.cc/vTTNTMkr/parque-oriental.png',
        inauguracion: '',
        localidad: 'Abayubá',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Oriental'
    },
    {
        id: 61,
        nombre: 'Parque Dr. Enrique Falco Lichtemberger',
        capacidad: 1500,
        propietario: 'Albion Football Club,',
        imagen: 'https://i.postimg.cc/2yHN90Rw/lichtemberger.jpg',
        inauguracion: '',
        localidad: 'Unión',
        departamento: 'Montevideo',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Parque_Dr._Enrique_Falco_Lichtemberger'
    },
    {
        id: 62,
        nombre: 'Estadio C.A. Progreso',
        capacidad: 1500,
        propietario: 'Club Atlético Progreso (Estación Atlántida)',
        imagen: 'https://i.postimg.cc/RCpY86JX/progreso-atlantida.jpg',
        inauguracion: 1992,
        localidad: 'Estación Atlántida',
        departamento: 'Canelones',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_de_Progreso'
    },
    {
        id: 63,
        nombre: 'Complejo Anselmo Meirana',
        capacidad: 1500,
        propietario: 'Piriápolis Fútbol Club',
        imagen: 'https://i.postimg.cc/Y9Mcp5tR/meirana.jpg',
        inauguracion: 1972,
        localidad: 'Piriápolis',
        departamento: 'Maldonado',
        wikipedia: 'https://es.wikipedia.org/wiki/Estadio_Complejo_Anselmo_Meirana'
    }
];

export default estadios;